### ISSUE TITLE
Crashes Node-RED on include

### ISSUE THREAD

**Issue by waywardmaker** [furcan/KioskBoard#10]
I'm attempting to use KioskBoard in a Node-RED implementation running on Raspberry Pi OS.

I have installed using `npm install kioskboard` which appears to have succeeded with kioskboard being installed in the `.node-red/node_modules/kioskboard` directory.

I am including KioskBoard in the Node-RED settings.js through:

```
functionGlobalContext: { KioskBoard:require('kioskboard') },
```

This fails on Node-RED loading with the following errors:

```
TypeError: Cannot read property 'prototype' of undefined
    at /home/pi/.node-red/node_modules/kioskboard/dist/kioskboard-aio-1.3.3.min.js:3:24247
    at /home/pi/.node-red/node_modules/kioskboard/dist/kioskboard-aio-1.3.3.min.js:3:24269
    at /home/pi/.node-red/node_modules/kioskboard/dist/kioskboard-aio-1.3.3.min.js:3:161
    at Object.<anonymous> (/home/pi/.node-red/node_modules/kioskboard/dist/kioskboard-aio-1.3.3.min.js:3:185)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

Any ideas on why this would be happening?

**Comment by furcan** [comment]
Hi @waywardmaker .

Could you please import the KioskBoard from `src/all-in-one/kioskboard-aio.js` to see the exact line of this issue?

Because it is hard to understand this issue on the minified scripts.

Thank you.

Furkan.
