### ISSUE TITLE
[BUG] - issues with rendering

### ISSUE THREAD

**Issue by chevonmdphillip** [furcan/KioskBoard#71]
![Greenshot 2022-11-16 21 19 25](https://user-images.githubusercontent.com/49420050/202338545-253984b6-d17c-44c2-87aa-574ab9cf792d.png)

**Comment by chevonmdphillip** [comment]
![Greenshot 2022-11-16 21 20 55](https://user-images.githubusercontent.com/49420050/202338707-a0a9aaab-63fd-4d21-8f9f-d8d399a57cee.png)

**Comment by chevonmdphillip** [comment]
```
TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at Object.run (/Users/chevy/Dev/Projects/SSTK/riddle/light-flicker-phone-v2/node_modules/kioskboard/dist/kioskboard-aio-2.3.0.min.js:3:26105)
    at file:///Users/chevy/Dev/Projects/SSTK/riddle/light-flicker-phone-v2/index.js:64:12
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:518:24)
    at async loadESM (node:internal/process/esm_loader:102:5)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v19.0.0
```

**Comment by furcan** [comment]
Hello.
KioskBoard uses UMD.
ESM is not supported.
Thanks.

**Comment by chevonmdphillip** [comment]
okay noob here. how do i add UMD to get this to work?

**Comment by chevonmdphillip** [comment]
Thanks, I got it figured out, and works great. Thanks to [https://vitejs.dev/](url)
